networks:
  rabbitmq_network:
    name: rabbitmq_network
    driver: bridge

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    networks:
      - rabbitmq_network  
    ports:
      - "11434:11434"
    volumes:
      - ./docker/ollama:/root/.ollama
    environment:
    - OLLAMA_KEEP_ALIVE=-1        # 10m = unload if unused for 10 minutes # -1 keeps the model in memory indefinitely (needs high VRAM!!!)
    - OLLAMA_MODEL=${LLM_MODEL}   # Comma-separated model list (your .env)
    # - OLLAMA_DEBUG=1              # verbose logs
    - OLLAMA_REQUEST_TIMEOUT=120  # increase timeouts
    - OLLAMA_RUN_TIMEOUT=300
    - OLLAMA_LOAD_TIMEOUT=30m
    - NVIDIA_VISIBLE_DEVICES=all  # <-- Expose all GPUs
    - NVIDIA_DRIVER_CAPABILITIES=compute,utility  # <-- Enable full CUDA performance
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all # <-- Use ALL GPUs (change to 1 if you want just 1 GPU)
              capabilities: [gpu]
    restart: unless-stopped # always
    
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    networks:
      - rabbitmq_network
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always

  fastapi:
    build:
      context: ./docker
      dockerfile: fastapi/Dockerfile
    container_name: fastapi_service
    networks:
      - rabbitmq_network
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - ollama
    volumes:
      - shared_volume:/fastapi/uploads
      - ./docker/translation_worker/translated:/translation_worker/translated
      - ./docker/translation_worker/temp:/translation_worker/temp
    restart: always

  translation_worker:
    build:
      context: ./docker
      dockerfile: translation_worker/Dockerfile
    container_name: translation_worker
    networks:
      - rabbitmq_network  
    depends_on:
      - rabbitmq
      - ollama
    volumes:
      - shared_volume:/fastapi/uploads
      - ./docker/translation_worker/temp:/translation_worker/temp
      - ./docker/translation_worker/profiles:/translation_worker/profiles
      - ./output:/output
    restart: always
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  # test_worker:
  #   build:
  #     context: ./docker
  #     dockerfile: test_worker/Dockerfile
  #   container_name: test_worker
  #   networks:
  #     - rabbitmq_network
  #   depends_on:
  #     - rabbitmq
  #     - ollama
  #   volumes:
  #     - shared_volume:/fastapi/uploads
  #     - ./docker/translation_worker/translated:/translation_worker/translated
  #     - ./docker/tests:/tests
  #     - ./output:/output
  #   restart: always
  #   env_file:
  #     - .env
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             capabilities: [gpu]

  model-preloader:
    build:
      context: ./docker
      dockerfile: model_loader/Dockerfile
    container_name: model_preloader
    depends_on:
      - ollama
    networks:
      - rabbitmq_network
    env_file:
      - .env
    environment:
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_URL=http://ollama:11434

volumes:
  shared_volume:
  rabbitmq_data:
